version: "3"
services:

  nginx.docker:
    container_name: "nodejs_nginx"
    image: nodejs_nginx
    user: root
    working_dir: /app/
    volumes:
      - ./:/app/
    expose:
      - 3000
      - 80
    ports:
      - 3000:3000
      - 80:80
    command: "/./app/docker/nginx/start.sh"

